services:
  # -----------------------------------------------------------------
  # BANCO DE DADOS (Postgres)
  # -----------------------------------------------------------------
  postgres:
    image: postgres:16-alpine
    container_name: postgres_container
    restart: always
    env_file:
      - .env  # Lê o .env para obter as variáveis de ambiente
    ports:
      - "${DB_PORT}:5432" # Porta externa:interna
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # -----------------------------------------------------------------
  # PGADMIN (Interface Visual)
  # -----------------------------------------------------------------
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      - postgres

  # -----------------------------------------------------------------
  # MAILPIT (Servidor Falso de E-mail)
  # -----------------------------------------------------------------
  mailpit:
    image: axllent/mailpit
    container_name: mailpit_container
    restart: always
    ports:
      - "8025:8025" # Interface Web (A "caixa de entrada" no navegador)
      - "1025:1025" # Porta SMTP (Para testar via código externo, se precisar)
    environment:
      MP_MAX_MESSAGES: 500

  # -----------------------------------------------------------------
  # API (Sua Aplicação Go)
  # -----------------------------------------------------------------
  api:
    container_name: api_epi
    restart: always
    build:
      context: .           # <--- O PULO DO GATO: Define a raiz do projeto como contexto
      dockerfile: Dockerfile # Aponta onde está o arquivo de build
    depends_on:
      - postgres
      - mailpit # <-- Adicionado para a API esperar o Mailpit subir
    env_file:
      -  .env
    environment:
      # Sobrescreve o DB_HOST para usar o nome do container
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      # --- Configurações do Servidor de Email ---
      - SMTP_HOST=mailpit # <-- O Pulo do Gato do Docker!
      - SMTP_PORT=1025
       
  nginx:
    image: nginx:alpine
    ports:
      - "80:80" # Porta que você vai acessar no http://localhost
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

volumes:
  postgres_data: