events {
    worker_connections 1024;
}

http {
    limit_req_zone $binary_remote_addr zone=limite_api:10m rate=5r/s;
    limit_req_status 429;

    server {
        listen 80;
        server_name localhost;

        location /api/ {
            limit_req zone=limite_api burst=10 nodelay;
            
            # Aqui vai a porta interna que o seu Go roda (ex: 8080 ou 3000)
            proxy_pass http://gestao-de-epi--backend.railway.internal:8080/; 
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }


        location /ws {
            proxy_pass http://gestao-de-epi--backend.railway.internal:8080/ws;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }

        location / {
            default_type text/plain;
            return 404 "A API SGE esta rodando em /api/";
       
        }

     }
}
