events {
    worker_connections 1024;
}

http {
    # Removidas as linhas de limit_req_zone para evitar o erro 429 localmente

    server {
        listen 80;
        server_name localhost;

        location /api/ {
            # O proxy_pass deve terminar com / se você quer que o Nginx remova o prefixo /api/
            # Ex: http://localhost/api/epis -> http://api_epi:8080/epis
            proxy_pass http://api_epi:8080; 
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Importante para o CORS e Headers customizados
            proxy_pass_request_headers on;
        }

        location / {
            default_type text/plain;
            return 404 "A API SGE esta rodando em /api/";
        }
    }
}