// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: Departamento.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const buscarDepartamento = `-- name: BuscarDepartamento :one
SELECT id, nome 
FROM departamento 
WHERE id = $1 
  AND tenant_id = $2 
  AND ativo = TRUE 
LIMIT 1
`

type BuscarDepartamentoParams struct {
	ID       int32
	TenantID int32
}

type BuscarDepartamentoRow struct {
	ID   int32
	Nome string
}

func (q *Queries) BuscarDepartamento(ctx context.Context, arg BuscarDepartamentoParams) (BuscarDepartamentoRow, error) {
	row := q.db.QueryRow(ctx, buscarDepartamento, arg.ID, arg.TenantID)
	var i BuscarDepartamentoRow
	err := row.Scan(&i.ID, &i.Nome)
	return i, err
}

const buscarTodosDepartamentos = `-- name: BuscarTodosDepartamentos :many
SELECT id, nome as departamento,
COUNT(*) OVER() AS total_geral
FROM departamento 
WHERE tenant_id = $3 
  AND ($4::text IS NULL OR nome ILIKE '%' || $4 || '%')
  AND ($5::int IS NULL OR id = $5::int)
  AND (

    ($6::boolean IS FALSE AND deletado_em IS NULL) OR
    ($6::boolean IS TRUE AND deletado_em IS NOT NULL)
  )
ORDER BY nome ASC
LIMIT $1 OFFSET $2
`

type BuscarTodosDepartamentosParams struct {
	Limit      int32
	Offset     int32
	TenantID   int32
	Nome       pgtype.Text
	ID         pgtype.Int4
	Cancelados bool
}

type BuscarTodosDepartamentosRow struct {
	ID           int32
	Departamento string
	TotalGeral   int64
}

func (q *Queries) BuscarTodosDepartamentos(ctx context.Context, arg BuscarTodosDepartamentosParams) ([]BuscarTodosDepartamentosRow, error) {
	rows, err := q.db.Query(ctx, buscarTodosDepartamentos,
		arg.Limit,
		arg.Offset,
		arg.TenantID,
		arg.Nome,
		arg.ID,
		arg.Cancelados,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarTodosDepartamentosRow
	for rows.Next() {
		var i BuscarTodosDepartamentosRow
		if err := rows.Scan(&i.ID, &i.Departamento, &i.TotalGeral); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const criaDepartamento = `-- name: CriaDepartamento :exec
INSERT INTO departamento (tenant_id, nome) 
VALUES ($1, $2)
`

type CriaDepartamentoParams struct {
	TenantID int32
	Nome     string
}

func (q *Queries) CriaDepartamento(ctx context.Context, arg CriaDepartamentoParams) error {
	_, err := q.db.Exec(ctx, criaDepartamento, arg.TenantID, arg.Nome)
	return err
}

const deletarDepartamento = `-- name: DeletarDepartamento :execrows
UPDATE departamento
SET ativo = FALSE,
    deletado_em = NOW()
WHERE id = $1 
  AND tenant_id = $2 
  AND ativo = TRUE
`

type DeletarDepartamentoParams struct {
	ID       int32
	TenantID int32
}

func (q *Queries) DeletarDepartamento(ctx context.Context, arg DeletarDepartamentoParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletarDepartamento, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDepartamento = `-- name: UpdateDepartamento :execrows
UPDATE departamento
SET nome = $2
WHERE id = $1 
  AND tenant_id = $3 
  AND ativo = TRUE
`

type UpdateDepartamentoParams struct {
	ID       int32
	Nome     string
	TenantID int32
}

func (q *Queries) UpdateDepartamento(ctx context.Context, arg UpdateDepartamentoParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDepartamento, arg.ID, arg.Nome, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
