// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Devolucao.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addDevolucaoSimples = `-- name: AddDevolucaoSimples :exec
INSERT INTO devolucao (
    tenant_id, IdFuncionario, IdEpi, IdMotivo, data_devolucao, IdTamanho, 
    quantidadeAdevolver, assinatura_digital, id_usuario_cancelamento, token_validacao
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type AddDevolucaoSimplesParams struct {
	TenantID              int32
	Idfuncionario         int32
	Idepi                 int32
	Idmotivo              int32
	DataDevolucao         pgtype.Date
	Idtamanho             int32
	Quantidadeadevolver   int32
	AssinaturaDigital     string
	IDUsuarioCancelamento pgtype.Int4
	TokenValidacao        pgtype.Text
}

func (q *Queries) AddDevolucaoSimples(ctx context.Context, arg AddDevolucaoSimplesParams) error {
	_, err := q.db.Exec(ctx, addDevolucaoSimples,
		arg.TenantID,
		arg.Idfuncionario,
		arg.Idepi,
		arg.Idmotivo,
		arg.DataDevolucao,
		arg.Idtamanho,
		arg.Quantidadeadevolver,
		arg.AssinaturaDigital,
		arg.IDUsuarioCancelamento,
		arg.TokenValidacao,
	)
	return err
}

const addEntregaVinculada = `-- name: AddEntregaVinculada :one
INSERT INTO entrega_epi (tenant_id, IdFuncionario, data_entrega, assinatura, IdTroca)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type AddEntregaVinculadaParams struct {
	TenantID      int32
	Idfuncionario int32
	DataEntrega   pgtype.Date
	Assinatura    string
	Idtroca       pgtype.Int4
}

func (q *Queries) AddEntregaVinculada(ctx context.Context, arg AddEntregaVinculadaParams) (int32, error) {
	row := q.db.QueryRow(ctx, addEntregaVinculada,
		arg.TenantID,
		arg.Idfuncionario,
		arg.DataEntrega,
		arg.Assinatura,
		arg.Idtroca,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const addTrocaEpi = `-- name: AddTrocaEpi :one
INSERT INTO devolucao (
    tenant_id, IdFuncionario, IdEpi, IdMotivo, data_devolucao, IdTamanho, 
    quantidadeAdevolver, IdEpiNovo, IdTamanhoNovo, quantidadeNova, assinatura_digital,id_usuario_cancelamento, token_validacao, houve_troca, observacao
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id
`

type AddTrocaEpiParams struct {
	TenantID              int32
	Idfuncionario         int32
	Idepi                 int32
	Idmotivo              int32
	DataDevolucao         pgtype.Date
	Idtamanho             int32
	Quantidadeadevolver   int32
	Idepinovo             pgtype.Int4
	Idtamanhonovo         pgtype.Int4
	Quantidadenova        pgtype.Int4
	AssinaturaDigital     string
	IDUsuarioCancelamento pgtype.Int4
	TokenValidacao        pgtype.Text
	HouveTroca            pgtype.Bool
	Observacao            pgtype.Text
}

func (q *Queries) AddTrocaEpi(ctx context.Context, arg AddTrocaEpiParams) (int32, error) {
	row := q.db.QueryRow(ctx, addTrocaEpi,
		arg.TenantID,
		arg.Idfuncionario,
		arg.Idepi,
		arg.Idmotivo,
		arg.DataDevolucao,
		arg.Idtamanho,
		arg.Quantidadeadevolver,
		arg.Idepinovo,
		arg.Idtamanhonovo,
		arg.Quantidadenova,
		arg.AssinaturaDigital,
		arg.IDUsuarioCancelamento,
		arg.TokenValidacao,
		arg.HouveTroca,
		arg.Observacao,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const atualizarSaldoLote = `-- name: AtualizarSaldoLote :exec

UPDATE entrada_epi_item
SET quantidade_atual = $2
WHERE id = $1 AND tenant_id = $3
`

type AtualizarSaldoLoteParams struct {
	ID              int32
	QuantidadeAtual int32
	TenantID        int32
}

// Pega do lote mais recente para o mais antigo
// Atualiza o saldo de um lote específico
func (q *Queries) AtualizarSaldoLote(ctx context.Context, arg AtualizarSaldoLoteParams) error {
	_, err := q.db.Exec(ctx, atualizarSaldoLote, arg.ID, arg.QuantidadeAtual, arg.TenantID)
	return err
}

const cancelarDevolucao = `-- name: CancelarDevolucao :one
UPDATE devolucao
SET cancelada_em = current_date,
    ativo = FALSE,
    id_usuario_devolucao_cancelamento = $2
WHERE id = $1 
  AND tenant_id = $3 -- SEGURANÇA: Só cancela se pertencer à empresa correta
  AND cancelada_em IS NULL
RETURNING id
`

type CancelarDevolucaoParams struct {
	ID                             int32
	IDUsuarioDevolucaoCancelamento pgtype.Int4
	TenantID                       int32
}

func (q *Queries) CancelarDevolucao(ctx context.Context, arg CancelarDevolucaoParams) (int32, error) {
	row := q.db.QueryRow(ctx, cancelarDevolucao, arg.ID, arg.IDUsuarioDevolucaoCancelamento, arg.TenantID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const consultarSaldoEpiFuncionario = `-- name: ConsultarSaldoEpiFuncionario :one
SELECT
    (
        -- Total já entregue para este funcionário
        COALESCE((
            SELECT SUM(eei.quantidade)::int
            FROM epis_entregues eei
            JOIN entrega_epi ee ON ee.id = eei.id_entrega_cabecalho
            WHERE ee.idfuncionario = $1
              AND eei.id_epi = $2
              AND eei.id_tamanho = $3
              AND ee.tenant_id = $4
        ), 0)
        -
        -- Menos o total que ele já devolveu anteriormente
        COALESCE((
            SELECT SUM(d.quantidadeadevolver)::int
            FROM devolucao d
            WHERE d.idfuncionario = $1
              AND d.idepi = $2
              AND d.idtamanho = $3
              AND d.tenant_id = $4
        ), 0)
    )::int AS saldo
`

type ConsultarSaldoEpiFuncionarioParams struct {
	Idfuncionario int32
	IDEpi         int32
	IDTamanho     int32
	TenantID      int32
}

func (q *Queries) ConsultarSaldoEpiFuncionario(ctx context.Context, arg ConsultarSaldoEpiFuncionarioParams) (int32, error) {
	row := q.db.QueryRow(ctx, consultarSaldoEpiFuncionario,
		arg.Idfuncionario,
		arg.IDEpi,
		arg.IDTamanho,
		arg.TenantID,
	)
	var saldo int32
	err := row.Scan(&saldo)
	return saldo, err
}

const listarDevolucoes = `-- name: ListarDevolucoes :many
select d.id, d.data_devolucao, d.idfuncionario, f.nome as funcionarioNome, f.matricula, e.nome as epiNome, 
t.tamanho, d.quantidadeadevolver, m.motivo, d.houve_troca, en.nome as epiNovo, tn.tamanho as tamanhoNovo,
d.quantidadenova,d.observacao, d.assinatura_digital, d.token_validacao
from devolucao d
inner join funcionario f on f.id = d.idfuncionario 
inner join epi e on e.id = d.idepi
full outer join epi en on en.id = d.idepinovo
inner join tamanhos_epis te on te.idtamanho = d.idtamanho
full outer join tamanho tn ON tn.id = d.idtamanhonovo
inner join tamanho t on t.id = te.idtamanho
inner join motivo_devolucao m on m.id = d.idmotivo
where d.tenant_id = $1 and d.cancelada_em is null
order by d.data_devolucao desc
`

type ListarDevolucoesRow struct {
	ID                  int32
	DataDevolucao       pgtype.Date
	Idfuncionario       int32
	Funcionarionome     string
	Matricula           int32
	Epinome             string
	Tamanho             string
	Quantidadeadevolver int32
	Motivo              string
	HouveTroca          pgtype.Bool
	Epinovo             pgtype.Text
	Tamanhonovo         pgtype.Text
	Quantidadenova      pgtype.Int4
	Observacao          pgtype.Text
	AssinaturaDigital   string
	TokenValidacao      pgtype.Text
}

func (q *Queries) ListarDevolucoes(ctx context.Context, tenantID int32) ([]ListarDevolucoesRow, error) {
	rows, err := q.db.Query(ctx, listarDevolucoes, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarDevolucoesRow
	for rows.Next() {
		var i ListarDevolucoesRow
		if err := rows.Scan(
			&i.ID,
			&i.DataDevolucao,
			&i.Idfuncionario,
			&i.Funcionarionome,
			&i.Matricula,
			&i.Epinome,
			&i.Tamanho,
			&i.Quantidadeadevolver,
			&i.Motivo,
			&i.HouveTroca,
			&i.Epinovo,
			&i.Tamanhonovo,
			&i.Quantidadenova,
			&i.Observacao,
			&i.AssinaturaDigital,
			&i.TokenValidacao,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarLotesParaRepor = `-- name: ListarLotesParaRepor :many
SELECT id, quantidade, quantidade_atual 
FROM entrada_epi_item
WHERE tenant_id = $1 
  AND id_epi = $2 
  AND id_tamanho = $3
  AND ativo = TRUE
  AND quantidade_atual < quantidade
ORDER BY id DESC
`

type ListarLotesParaReporParams struct {
	TenantID  int32
	IDEpi     int32
	IDTamanho int32
}

type ListarLotesParaReporRow struct {
	ID              int32
	Quantidade      int32
	QuantidadeAtual int32
}

// Busca todos os lotes que ainda têm espaço para receber devolução (quantidade_atual < quantidade)
func (q *Queries) ListarLotesParaRepor(ctx context.Context, arg ListarLotesParaReporParams) ([]ListarLotesParaReporRow, error) {
	rows, err := q.db.Query(ctx, listarLotesParaRepor, arg.TenantID, arg.IDEpi, arg.IDTamanho)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarLotesParaReporRow
	for rows.Next() {
		var i ListarLotesParaReporRow
		if err := rows.Scan(&i.ID, &i.Quantidade, &i.QuantidadeAtual); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
