// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Empresa.sql

package repository

import (
	"context"
)

const getTenantBySubdomain = `-- name: GetTenantBySubdomain :one
SELECT id, nome_fantasia 
FROM empresas 
WHERE subdominio = $1 AND ativo = TRUE
`

type GetTenantBySubdomainRow struct {
	ID           int32
	NomeFantasia string
}

func (q *Queries) GetTenantBySubdomain(ctx context.Context, subdominio string) (GetTenantBySubdomainRow, error) {
	row := q.db.QueryRow(ctx, getTenantBySubdomain, subdominio)
	var i GetTenantBySubdomainRow
	err := row.Scan(&i.ID, &i.NomeFantasia)
	return i, err
}
