// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: EntradaEpi.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelarEntrada = `-- name: CancelarEntrada :execrows
UPDATE entrada_epi_item 
SET 
    cancelada_em = CURRENT_TIMESTAMP, 
    ativo = FALSE,
    id_usuario_cancelamento = $2 -- <-- O sqlc vai gerar IDUsuarioCancelamento
WHERE id = $1 
  AND tenant_id = $3
  AND cancelada_em IS NULL
`

type CancelarEntradaParams struct {
	ID                    int32
	IDUsuarioCancelamento pgtype.Int4
	TenantID              int32
}

func (q *Queries) CancelarEntrada(ctx context.Context, arg CancelarEntradaParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelarEntrada, arg.ID, arg.IDUsuarioCancelamento, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const contarEntradasFiltradas = `-- name: ContarEntradasFiltradas :one
SELECT COUNT(*) 
FROM entrada_epi_item ei
INNER JOIN entrada_nf nf ON ei.entrada_nf_id = nf.id
WHERE 
    ei.tenant_id = $1
    AND (
        ($2::boolean IS FALSE AND ei.cancelada_em IS NULL) OR
        ($2::boolean IS TRUE AND ei.cancelada_em IS NOT NULL)
    )
    AND ($3::int IS NULL OR ei.id_epi = $3)
    AND ($4::date IS NULL OR nf.data_emissao >= $4)
    AND ($5::text IS NULL OR nf.nota_fiscal_numero ILIKE '%' || $5 || '%')
`

type ContarEntradasFiltradasParams struct {
	TenantID   int32
	Canceladas bool
	IDEpi      pgtype.Int4
	DataInicio pgtype.Date
	NotaFiscal pgtype.Text
}

func (q *Queries) ContarEntradasFiltradas(ctx context.Context, arg ContarEntradasFiltradasParams) (int64, error) {
	row := q.db.QueryRow(ctx, contarEntradasFiltradas,
		arg.TenantID,
		arg.Canceladas,
		arg.IDEpi,
		arg.DataInicio,
		arg.NotaFiscal,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEntradaEpiItem = `-- name: CreateEntradaEpiItem :exec
INSERT INTO entrada_epi_item (
    tenant_id, entrada_nf_id, id_epi, id_tamanho, quantidade, 
    quantidade_atual, data_fabricacao, data_validade, lote, valor_unitario,id_usuario_criacao
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateEntradaEpiItemParams struct {
	TenantID         int32
	EntradaNfID      int32
	IDEpi            int32
	IDTamanho        int32
	Quantidade       int32
	QuantidadeAtual  int32
	DataFabricacao   pgtype.Date
	DataValidade     pgtype.Date
	Lote             string
	ValorUnitario    pgtype.Numeric
	IDUsuarioCriacao int32
}

func (q *Queries) CreateEntradaEpiItem(ctx context.Context, arg CreateEntradaEpiItemParams) error {
	_, err := q.db.Exec(ctx, createEntradaEpiItem,
		arg.TenantID,
		arg.EntradaNfID,
		arg.IDEpi,
		arg.IDTamanho,
		arg.Quantidade,
		arg.QuantidadeAtual,
		arg.DataFabricacao,
		arg.DataValidade,
		arg.Lote,
		arg.ValorUnitario,
		arg.IDUsuarioCriacao,
	)
	return err
}

const createEntradaNF = `-- name: CreateEntradaNF :one
INSERT INTO entrada_nf (tenant_id, nota_fiscal_numero, nota_fiscal_serie, data_emissao, id_usuario_criacao, Idfornecedor)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateEntradaNFParams struct {
	TenantID         int32
	NotaFiscalNumero string
	NotaFiscalSerie  pgtype.Text
	DataEmissao      pgtype.Date
	IDUsuarioCriacao int32
	Idfornecedor     int32
}

func (q *Queries) CreateEntradaNF(ctx context.Context, arg CreateEntradaNFParams) (int32, error) {
	row := q.db.QueryRow(ctx, createEntradaNF,
		arg.TenantID,
		arg.NotaFiscalNumero,
		arg.NotaFiscalSerie,
		arg.DataEmissao,
		arg.IDUsuarioCriacao,
		arg.Idfornecedor,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const entradaDashbord = `-- name: EntradaDashbord :many
SELECT
    ei.id, ei.id_epi, ei.id_tamanho, ei.quantidade_atual, ei.valor_unitario, ei.quantidade,
    nf.data_emissao as data_entrada, ei.lote
FROM entrada_epi_item ei
INNER JOIN entrada_nf nf ON ei.entrada_nf_id = nf.id
WHERE ei.tenant_id = $1 AND ei.ativo = TRUE
ORDER BY nf.data_emissao DESC
`

type EntradaDashbordRow struct {
	ID              int32
	IDEpi           int32
	IDTamanho       int32
	QuantidadeAtual int32
	ValorUnitario   pgtype.Numeric
	Quantidade      int32
	DataEntrada     pgtype.Date
	Lote            string
}

func (q *Queries) EntradaDashbord(ctx context.Context, tenantID int32) ([]EntradaDashbordRow, error) {
	rows, err := q.db.Query(ctx, entradaDashbord, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntradaDashbordRow
	for rows.Next() {
		var i EntradaDashbordRow
		if err := rows.Scan(
			&i.ID,
			&i.IDEpi,
			&i.IDTamanho,
			&i.QuantidadeAtual,
			&i.ValorUnitario,
			&i.Quantidade,
			&i.DataEntrada,
			&i.Lote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entradaEpiEstoque = `-- name: EntradaEpiEstoque :many
SELECT
    ei.id, ei.lote, ei.quantidade as quantidade_inicial, ei.quantidade_atual,
    ei.valor_unitario, ei.data_validade,
    ei.id_tamanho, t.tamanho as tamanho_nome,
    ei.id_epi, e.nome as epi_nome, e.fabricante, e.ca, e.descricao, e.validade_ca, e.alerta_minimo,
    e.idtipoprotecao, tp.nome as protecao_nome,
    nf.data_emissao as data_entrada
FROM entrada_epi_item ei
INNER JOIN entrada_nf nf ON ei.entrada_nf_id = nf.id
INNER JOIN tamanho t ON ei.id_tamanho = t.id
INNER JOIN epi e ON ei.id_epi = e.id
INNER JOIN tipo_protecao tp ON e.idtipoprotecao = tp.id
WHERE ei.tenant_id = $1
  AND ei.ativo = TRUE
ORDER BY nf.data_emissao ASC
`

type EntradaEpiEstoqueRow struct {
	ID                int32
	Lote              string
	QuantidadeInicial int32
	QuantidadeAtual   int32
	ValorUnitario     pgtype.Numeric
	DataValidade      pgtype.Date
	IDTamanho         int32
	TamanhoNome       string
	IDEpi             int32
	EpiNome           string
	Fabricante        string
	Ca                string
	Descricao         string
	ValidadeCa        pgtype.Date
	AlertaMinimo      int32
	Idtipoprotecao    int32
	ProtecaoNome      string
	DataEntrada       pgtype.Date
}

func (q *Queries) EntradaEpiEstoque(ctx context.Context, tenantID int32) ([]EntradaEpiEstoqueRow, error) {
	rows, err := q.db.Query(ctx, entradaEpiEstoque, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntradaEpiEstoqueRow
	for rows.Next() {
		var i EntradaEpiEstoqueRow
		if err := rows.Scan(
			&i.ID,
			&i.Lote,
			&i.QuantidadeInicial,
			&i.QuantidadeAtual,
			&i.ValorUnitario,
			&i.DataValidade,
			&i.IDTamanho,
			&i.TamanhoNome,
			&i.IDEpi,
			&i.EpiNome,
			&i.Fabricante,
			&i.Ca,
			&i.Descricao,
			&i.ValidadeCa,
			&i.AlertaMinimo,
			&i.Idtipoprotecao,
			&i.ProtecaoNome,
			&i.DataEntrada,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarEntradas = `-- name: ListarEntradas :many
SELECT 
    ei.id, 
    ei.id_epi, 
    e.nome as epi_nome, 
    e.fabricante, 
    e.ca, 
    e.descricao as epi_descricao,
    ei.data_fabricacao, 
    ei.data_validade, 
    e.validade_ca,
    e.IdTipoProtecao, 
    tp.nome as protecao_nome,
    ei.id_tamanho, 
    t.tamanho as tamanho_nome, 
    ei.quantidade, 
    ei.quantidade_atual, 
    nf.data_emissao as data_entrada, -- Vem da NF agora
    ei.lote,
    ei.valor_unitario, 
    nf.Idfornecedor,
    f.nome_fantasia,
    f.razao_social,
    nf.nota_fiscal_numero, 
    nf.nota_fiscal_serie, 
    ei.cancelada_em,
	us.nome as usuario_criacao
FROM entrada_epi_item ei
INNER JOIN entrada_nf nf ON ei.entrada_nf_id = nf.id
INNER JOIN fornecedores f ON nf.Idfornecedor = f.id
INNER JOIN epi e ON ei.id_epi = e.id
INNER JOIN tipo_protecao tp ON e.idtipoprotecao = tp.id
INNER JOIN tamanho t ON ei.id_tamanho = t.id
INNER JOIN usuarios us ON us.id = nf.id_usuario_criacao
WHERE 
    ei.tenant_id = $1
    AND (
        ($2::boolean IS FALSE AND ei.cancelada_em IS NULL) OR
        ($2::boolean IS TRUE AND ei.cancelada_em IS NOT NULL)
    )
    AND ($3::int IS NULL OR ei.id_epi = $3)
    AND ($4::int IS NULL OR ei.id = $4)
    AND ($5::date IS NULL OR nf.data_emissao >= $5)
    AND ($6::date IS NULL OR nf.data_emissao <= $6)
    AND ($7::text IS NULL OR nf.nota_fiscal_numero ILIKE '%' || $7 || '%')
ORDER BY nf.data_emissao DESC
LIMIT $9 OFFSET $8
`

type ListarEntradasParams struct {
	TenantID   int32
	Canceladas bool
	IDEpi      pgtype.Int4
	IDEntrada  pgtype.Int4
	DataInicio pgtype.Date
	DataFim    pgtype.Date
	NotaFiscal pgtype.Text
	Offset     int32
	Limit      int32
}

type ListarEntradasRow struct {
	ID               int32
	IDEpi            int32
	EpiNome          string
	Fabricante       string
	Ca               string
	EpiDescricao     string
	DataFabricacao   pgtype.Date
	DataValidade     pgtype.Date
	ValidadeCa       pgtype.Date
	Idtipoprotecao   int32
	ProtecaoNome     string
	IDTamanho        int32
	TamanhoNome      string
	Quantidade       int32
	QuantidadeAtual  int32
	DataEntrada      pgtype.Date
	Lote             string
	ValorUnitario    pgtype.Numeric
	Idfornecedor     int32
	NomeFantasia     string
	RazaoSocial      string
	NotaFiscalNumero string
	NotaFiscalSerie  pgtype.Text
	CanceladaEm      pgtype.Timestamp
	UsuarioCriacao   string
}

func (q *Queries) ListarEntradas(ctx context.Context, arg ListarEntradasParams) ([]ListarEntradasRow, error) {
	rows, err := q.db.Query(ctx, listarEntradas,
		arg.TenantID,
		arg.Canceladas,
		arg.IDEpi,
		arg.IDEntrada,
		arg.DataInicio,
		arg.DataFim,
		arg.NotaFiscal,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarEntradasRow
	for rows.Next() {
		var i ListarEntradasRow
		if err := rows.Scan(
			&i.ID,
			&i.IDEpi,
			&i.EpiNome,
			&i.Fabricante,
			&i.Ca,
			&i.EpiDescricao,
			&i.DataFabricacao,
			&i.DataValidade,
			&i.ValidadeCa,
			&i.Idtipoprotecao,
			&i.ProtecaoNome,
			&i.IDTamanho,
			&i.TamanhoNome,
			&i.Quantidade,
			&i.QuantidadeAtual,
			&i.DataEntrada,
			&i.Lote,
			&i.ValorUnitario,
			&i.Idfornecedor,
			&i.NomeFantasia,
			&i.RazaoSocial,
			&i.NotaFiscalNumero,
			&i.NotaFiscalSerie,
			&i.CanceladaEm,
			&i.UsuarioCriacao,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
