// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Epi.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addEpi = `-- name: AddEpi :one
INSERT INTO epi (tenant_id, nome, fabricante, CA, descricao, validade_CA, IdTipoProtecao, alerta_minimo) 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type AddEpiParams struct {
	TenantID       int32
	Nome           string
	Fabricante     string
	Ca             string
	Descricao      string
	ValidadeCa     pgtype.Date
	Idtipoprotecao int32
	AlertaMinimo   int32
}

func (q *Queries) AddEpi(ctx context.Context, arg AddEpiParams) (int32, error) {
	row := q.db.QueryRow(ctx, addEpi,
		arg.TenantID,
		arg.Nome,
		arg.Fabricante,
		arg.Ca,
		arg.Descricao,
		arg.ValidadeCa,
		arg.Idtipoprotecao,
		arg.AlertaMinimo,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const addEpiTamanho = `-- name: AddEpiTamanho :exec
INSERT INTO tamanhos_epis (tenant_id, IdEpi, IdTamanho, ativo, deletado_em) 
VALUES ($1, $2, $3, TRUE, NULL)
ON CONFLICT (IdEpi, IdTamanho, tenant_id) 
DO UPDATE SET ativo = TRUE, deletado_em = NULL
`

type AddEpiTamanhoParams struct {
	TenantID  int32
	Idepi     int32
	Idtamanho int32
}

func (q *Queries) AddEpiTamanho(ctx context.Context, arg AddEpiTamanhoParams) error {
	_, err := q.db.Exec(ctx, addEpiTamanho, arg.TenantID, arg.Idepi, arg.Idtamanho)
	return err
}

const buscaEpiDashbord = `-- name: BuscaEpiDashbord :many
SELECT id, nome, alerta_minimo
FROM epi
WHERE tenant_id = $1 -- SEGURANÇA
  AND ativo = TRUE
ORDER BY nome
`

type BuscaEpiDashbordRow struct {
	ID           int32
	Nome         string
	AlertaMinimo int32
}

func (q *Queries) BuscaEpiDashbord(ctx context.Context, tenantID int32) ([]BuscaEpiDashbordRow, error) {
	rows, err := q.db.Query(ctx, buscaEpiDashbord, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscaEpiDashbordRow
	for rows.Next() {
		var i BuscaEpiDashbordRow
		if err := rows.Scan(&i.ID, &i.Nome, &i.AlertaMinimo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const buscaItensEntreguesPorFuncionario = `-- name: BuscaItensEntreguesPorFuncionario :many
WITH Entregas AS (
    -- 1. Agrupa e soma todas as quantidades que o funcionário já recebeu por EPI e Tamanho
    SELECT 
        ee.id_epi, 
        ee.id_tamanho, 
        SUM(ee.quantidade)::int as total_entregue
    FROM epis_entregues ee
    INNER JOIN entrega_epi e ON e.id = ee.id_entrega_cabecalho
    WHERE e.tenant_id = $1 
      AND e.IdFuncionario = $2
      AND e.cancelada_em IS NULL
    GROUP BY ee.id_epi, ee.id_tamanho
),
Devolucoes AS (
    -- 2. Agrupa e soma tudo que ele já devolveu desse EPI e Tamanho
    SELECT 
      d.idepi, 
        d.idtamanho, 
        SUM(d.quantidadeadevolver)::int as total_devolvido
    FROM devolucao d
    WHERE d.tenant_id = $1 
      AND d.idfuncionario = $2
    GROUP BY d.idepi, d.idtamanho
)
SELECT 
    Entregas.id_epi,
    ep.nome as epi_nome,
    ep.fabricante,
    ep.ca,
    ep.descricao,
    ep.validade_ca,
    ep.alerta_minimo,
    ep.idtipoprotecao,
    tp.nome as tipo_protecao_nome,
    Entregas.id_tamanho,
    t.tamanho as tamanho_nome,
    (Entregas.total_entregue - COALESCE(Devolucoes.total_devolvido, 0))::int AS saldo_atual
FROM Entregas
LEFT JOIN Devolucoes 
    ON Entregas.id_epi = Devolucoes.idepi 
   AND Entregas.id_tamanho = Devolucoes.idtamanho
INNER JOIN epi ep ON ep.id = Entregas.id_epi
INNER JOIN tamanho t ON t.id = Entregas.id_tamanho
INNER JOIN tipo_protecao tp ON tp.id = ep.IdTipoProtecao
WHERE (Entregas.total_entregue - COALESCE(Devolucoes.total_devolvido, 0)) > 0
`

type BuscaItensEntreguesPorFuncionarioParams struct {
	TenantID      int32
	Idfuncionario int32
}

type BuscaItensEntreguesPorFuncionarioRow struct {
	IDEpi            int32
	EpiNome          string
	Fabricante       string
	Ca               string
	Descricao        string
	ValidadeCa       pgtype.Date
	AlertaMinimo     int32
	Idtipoprotecao   int32
	TipoProtecaoNome string
	IDTamanho        int32
	TamanhoNome      string
	SaldoAtual       int32
}

// 3. Junta as tabelas, traz os dados completos do EPI e filtra o saldo
func (q *Queries) BuscaItensEntreguesPorFuncionario(ctx context.Context, arg BuscaItensEntreguesPorFuncionarioParams) ([]BuscaItensEntreguesPorFuncionarioRow, error) {
	rows, err := q.db.Query(ctx, buscaItensEntreguesPorFuncionario, arg.TenantID, arg.Idfuncionario)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscaItensEntreguesPorFuncionarioRow
	for rows.Next() {
		var i BuscaItensEntreguesPorFuncionarioRow
		if err := rows.Scan(
			&i.IDEpi,
			&i.EpiNome,
			&i.Fabricante,
			&i.Ca,
			&i.Descricao,
			&i.ValidadeCa,
			&i.AlertaMinimo,
			&i.Idtipoprotecao,
			&i.TipoProtecaoNome,
			&i.IDTamanho,
			&i.TamanhoNome,
			&i.SaldoAtual,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const buscaTodosItensEntreguesDoTenant = `-- name: BuscaTodosItensEntreguesDoTenant :many
SELECT
    ee.id,
    ee.id_entrega_cabecalho, -- 🔑 CHAVE MESTRA: Liga o item à entrega correta no Go!
    ee.quantidade,
    ee.id_tamanho,
    t.tamanho as tamanho_nome,
    ee.id_epi,
    ep.nome as epi_nome,
    ep.fabricante,
    ep.CA,
    ep.descricao,
    ep.validade_CA,
    ep.alerta_minimo,
    ep.IdTipoProtecao,
    tp.nome as tipo_protecao_nome
FROM epis_entregues ee
INNER JOIN entrega_epi e ON e.id = ee.id_entrega_cabecalho
INNER JOIN epi ep ON ep.id = ee.id_epi
INNER JOIN tamanho t ON t.id = ee.id_tamanho
INNER JOIN tipo_protecao tp ON tp.id = ep.IdTipoProtecao
WHERE e.tenant_id = $1
`

type BuscaTodosItensEntreguesDoTenantRow struct {
	ID                 int32
	IDEntregaCabecalho int32
	Quantidade         int32
	IDTamanho          int32
	TamanhoNome        string
	IDEpi              int32
	EpiNome            string
	Fabricante         string
	Ca                 string
	Descricao          string
	ValidadeCa         pgtype.Date
	AlertaMinimo       int32
	Idtipoprotecao     int32
	TipoProtecaoNome   string
}

func (q *Queries) BuscaTodosItensEntreguesDoTenant(ctx context.Context, tenantID int32) ([]BuscaTodosItensEntreguesDoTenantRow, error) {
	rows, err := q.db.Query(ctx, buscaTodosItensEntreguesDoTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscaTodosItensEntreguesDoTenantRow
	for rows.Next() {
		var i BuscaTodosItensEntreguesDoTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.IDEntregaCabecalho,
			&i.Quantidade,
			&i.IDTamanho,
			&i.TamanhoNome,
			&i.IDEpi,
			&i.EpiNome,
			&i.Fabricante,
			&i.Ca,
			&i.Descricao,
			&i.ValidadeCa,
			&i.AlertaMinimo,
			&i.Idtipoprotecao,
			&i.TipoProtecaoNome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const buscarEpi = `-- name: BuscarEpi :one
SELECT 
    e.id, e.nome, e.fabricante, e.CA, e.descricao,
    e.validade_CA, e.alerta_minimo, e.IdTipoProtecao, 
    tp.nome as tipo_protecao_nome
FROM epi e
INNER JOIN tipo_protecao tp ON e.IdTipoProtecao = tp.id
WHERE e.id = $1 
  AND e.tenant_id = $2 -- SEGURANÇA
  AND e.ativo = TRUE
`

type BuscarEpiParams struct {
	ID       int32
	TenantID int32
}

type BuscarEpiRow struct {
	ID               int32
	Nome             string
	Fabricante       string
	Ca               string
	Descricao        string
	ValidadeCa       pgtype.Date
	AlertaMinimo     int32
	Idtipoprotecao   int32
	TipoProtecaoNome string
}

func (q *Queries) BuscarEpi(ctx context.Context, arg BuscarEpiParams) (BuscarEpiRow, error) {
	row := q.db.QueryRow(ctx, buscarEpi, arg.ID, arg.TenantID)
	var i BuscarEpiRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Fabricante,
		&i.Ca,
		&i.Descricao,
		&i.ValidadeCa,
		&i.AlertaMinimo,
		&i.Idtipoprotecao,
		&i.TipoProtecaoNome,
	)
	return i, err
}

const buscarTamanhosPorEpi = `-- name: BuscarTamanhosPorEpi :many
SELECT t.id, t.tamanho
FROM tamanho t
INNER JOIN tamanhos_epis te ON t.id = te.IdTamanho
WHERE te.IdEpi = $1 
  AND te.tenant_id = $2 -- SEGURANÇA: Garante que a relação pertence à empresa
  AND te.ativo = TRUE
`

type BuscarTamanhosPorEpiParams struct {
	Idepi    int32
	TenantID int32
}

type BuscarTamanhosPorEpiRow struct {
	ID      int32
	Tamanho string
}

func (q *Queries) BuscarTamanhosPorEpi(ctx context.Context, arg BuscarTamanhosPorEpiParams) ([]BuscarTamanhosPorEpiRow, error) {
	rows, err := q.db.Query(ctx, buscarTamanhosPorEpi, arg.Idepi, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarTamanhosPorEpiRow
	for rows.Next() {
		var i BuscarTamanhosPorEpiRow
		if err := rows.Scan(&i.ID, &i.Tamanho); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const buscarTodosEpisPaginado = `-- name: BuscarTodosEpisPaginado :many
SELECT 
    e.id, e.nome, e.fabricante, e.CA, e.descricao,
    e.validade_CA, e.alerta_minimo, e.IdTipoProtecao, 
    tp.nome as tipo_protecao_nome,
    COUNT(*) OVER() as total_geral
FROM epi e
INNER JOIN tipo_protecao tp ON e.IdTipoProtecao = tp.id
WHERE e.tenant_id = $3 -- SEGURANÇA: Filtro de Tenant
  AND ($4::text IS NULL OR e.nome ILIKE '%' || $4 || '%')
  AND ($5::text IS NULL OR e.CA ILIKE '%' || $5 || '%')
  AND ($6::int IS NULL OR e.id = $6::int)
  AND (
    ($7::boolean IS FALSE AND e.deletado_em IS NULL) OR
    ($7::boolean IS TRUE AND e.deletado_em IS NOT NULL)
  )
  AND ($8::text IS NULL OR e.fabricante ILIKE '%' || $8 || '%')
ORDER BY e.id
LIMIT $1 OFFSET $2
`

type BuscarTodosEpisPaginadoParams struct {
	Limit      int32
	Offset     int32
	TenantID   int32
	Nome       pgtype.Text
	Ca         pgtype.Text
	ID         pgtype.Int4
	Cancelados bool
	Fabricante pgtype.Text
}

type BuscarTodosEpisPaginadoRow struct {
	ID               int32
	Nome             string
	Fabricante       string
	Ca               string
	Descricao        string
	ValidadeCa       pgtype.Date
	AlertaMinimo     int32
	Idtipoprotecao   int32
	TipoProtecaoNome string
	TotalGeral       int64
}

func (q *Queries) BuscarTodosEpisPaginado(ctx context.Context, arg BuscarTodosEpisPaginadoParams) ([]BuscarTodosEpisPaginadoRow, error) {
	rows, err := q.db.Query(ctx, buscarTodosEpisPaginado,
		arg.Limit,
		arg.Offset,
		arg.TenantID,
		arg.Nome,
		arg.Ca,
		arg.ID,
		arg.Cancelados,
		arg.Fabricante,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarTodosEpisPaginadoRow
	for rows.Next() {
		var i BuscarTodosEpisPaginadoRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Fabricante,
			&i.Ca,
			&i.Descricao,
			&i.ValidadeCa,
			&i.AlertaMinimo,
			&i.Idtipoprotecao,
			&i.TipoProtecaoNome,
			&i.TotalGeral,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const buscarTodosTamanhosAgrupados = `-- name: BuscarTodosTamanhosAgrupados :many
SELECT te.IdEpi, t.id, t.tamanho
FROM tamanho t
INNER JOIN tamanhos_epis te ON t.id = te.IdTamanho
WHERE te.tenant_id = $1 -- SEGURANÇA
  AND te.ativo = TRUE
`

type BuscarTodosTamanhosAgrupadosRow struct {
	Idepi   int32
	ID      int32
	Tamanho string
}

func (q *Queries) BuscarTodosTamanhosAgrupados(ctx context.Context, tenantID int32) ([]BuscarTodosTamanhosAgrupadosRow, error) {
	rows, err := q.db.Query(ctx, buscarTodosTamanhosAgrupados, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarTodosTamanhosAgrupadosRow
	for rows.Next() {
		var i BuscarTodosTamanhosAgrupadosRow
		if err := rows.Scan(&i.Idepi, &i.ID, &i.Tamanho); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletarEpi = `-- name: DeletarEpi :execrows
UPDATE epi 
SET ativo = FALSE, deletado_em = current_date
WHERE id = $1 
  AND tenant_id = $2 -- SEGURANÇA
  AND ativo = TRUE
`

type DeletarEpiParams struct {
	ID       int32
	TenantID int32
}

func (q *Queries) DeletarEpi(ctx context.Context, arg DeletarEpiParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletarEpi, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletarTamanhosPorEpi = `-- name: DeletarTamanhosPorEpi :execrows

DELETE FROM tamanhos_epis 
WHERE IdEpi = $1 AND tenant_id = $2
`

type DeletarTamanhosPorEpiParams struct {
	Idepi    int32
	TenantID int32
}

func (q *Queries) DeletarTamanhosPorEpi(ctx context.Context, arg DeletarTamanhosPorEpiParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletarTamanhosPorEpi, arg.Idepi, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEpiCampo = `-- name: UpdateEpiCampo :execrows
UPDATE epi 
SET 
    nome = COALESCE($1, nome),
    fabricante = COALESCE($2, fabricante),
    CA = COALESCE($3, CA),
    descricao = COALESCE($4, descricao),
    validade_CA = COALESCE($5, validade_CA),
    IdTipoProtecao = COALESCE($6::int, IdTipoProtecao),
    alerta_minimo = COALESCE($7::int, alerta_minimo)  
    WHERE id = $8 
  AND tenant_id = $9 -- SEGURANÇA: Obrigatório para update
  AND ativo = TRUE
`

type UpdateEpiCampoParams struct {
	Nome           pgtype.Text
	Fabricante     pgtype.Text
	Ca             pgtype.Text
	Descricao      pgtype.Text
	ValidadeCa     pgtype.Date
	IDTipoProtecao pgtype.Int4
	AlertaMinimo   pgtype.Int4
	ID             int32
	TenantID       int32
}

func (q *Queries) UpdateEpiCampo(ctx context.Context, arg UpdateEpiCampoParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEpiCampo,
		arg.Nome,
		arg.Fabricante,
		arg.Ca,
		arg.Descricao,
		arg.ValidadeCa,
		arg.IDTipoProtecao,
		arg.AlertaMinimo,
		arg.ID,
		arg.TenantID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
