// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: Estoque.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const abaterEstoqueLote = `-- name: AbaterEstoqueLote :execrows
UPDATE entrada_epi_item 
SET quantidade_atual = quantidade_atual - $1 
WHERE id = $2 
  AND tenant_id = $3 
  AND ativo = TRUE
  AND quantidade_atual >= $1
`

type AbaterEstoqueLoteParams struct {
	QuantidadeAtual int32
	ID              int32
	TenantID        int32
}

func (q *Queries) AbaterEstoqueLote(ctx context.Context, arg AbaterEstoqueLoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, abaterEstoqueLote, arg.QuantidadeAtual, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const devolverItemAoEstoque = `-- name: DevolverItemAoEstoque :exec
UPDATE entrada_epi_item
SET quantidade_atual = entrada_epi_item.quantidade_atual + $4 -- 👈 Explicitamos a tabela aqui
WHERE id = (
    SELECT eei.id
    FROM entrada_epi_item eei
    WHERE eei.tenant_id = $1 
      AND eei.id_epi = $2 
      AND eei.id_tamanho = $3
      AND eei.ativo = TRUE
    ORDER BY eei.id DESC 
    LIMIT 1
)
AND tenant_id = $1
`

type DevolverItemAoEstoqueParams struct {
	TenantID        int32
	IDEpi           int32
	IDTamanho       int32
	QuantidadeAtual int32
}

func (q *Queries) DevolverItemAoEstoque(ctx context.Context, arg DevolverItemAoEstoqueParams) error {
	_, err := q.db.Exec(ctx, devolverItemAoEstoque,
		arg.TenantID,
		arg.IDEpi,
		arg.IDTamanho,
		arg.QuantidadeAtual,
	)
	return err
}

const listarEstoqueAtual = `-- name: ListarEstoqueAtual :many
SELECT 
    e.id_epi, 
    p.nome AS nome_epi,
    SUM(e.quantidade_atual)::bigint AS quantidade_total,
    COUNT(*) OVER() AS total_geral
FROM entrada_epi_item e
INNER JOIN epi p ON e.id_epi = p.id
WHERE e.tenant_id = $3
  AND e.ativo = TRUE
GROUP BY e.id_epi, p.nome
LIMIT $1 OFFSET $2
`

type ListarEstoqueAtualParams struct {
	Limit    int32
	Offset   int32
	TenantID int32
}

type ListarEstoqueAtualRow struct {
	IDEpi           int32
	NomeEpi         string
	QuantidadeTotal int64
	TotalGeral      int64
}

func (q *Queries) ListarEstoqueAtual(ctx context.Context, arg ListarEstoqueAtualParams) ([]ListarEstoqueAtualRow, error) {
	rows, err := q.db.Query(ctx, listarEstoqueAtual, arg.Limit, arg.Offset, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarEstoqueAtualRow
	for rows.Next() {
		var i ListarEstoqueAtualRow
		if err := rows.Scan(
			&i.IDEpi,
			&i.NomeEpi,
			&i.QuantidadeTotal,
			&i.TotalGeral,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarLotesParaConsumo = `-- name: ListarLotesParaConsumo :many
SELECT id, quantidade_atual, data_validade, valor_unitario 
FROM entrada_epi_item 
WHERE tenant_id = $1 
  AND id_epi = $2 
  AND id_tamanho = $3 
  AND quantidade_atual > 0 
  AND data_validade >= CURRENT_DATE
  AND ativo = TRUE
ORDER BY data_validade ASC
FOR UPDATE
`

type ListarLotesParaConsumoParams struct {
	TenantID  int32
	IDEpi     int32
	IDTamanho int32
}

type ListarLotesParaConsumoRow struct {
	ID              int32
	QuantidadeAtual int32
	DataValidade    pgtype.Date
	ValorUnitario   pgtype.Numeric
}

// O PostgreSQL usa FOR UPDATE para travar apenas as linhas desse cliente específico.
func (q *Queries) ListarLotesParaConsumo(ctx context.Context, arg ListarLotesParaConsumoParams) ([]ListarLotesParaConsumoRow, error) {
	rows, err := q.db.Query(ctx, listarLotesParaConsumo, arg.TenantID, arg.IDEpi, arg.IDTamanho)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarLotesParaConsumoRow
	for rows.Next() {
		var i ListarLotesParaConsumoRow
		if err := rows.Scan(
			&i.ID,
			&i.QuantidadeAtual,
			&i.DataValidade,
			&i.ValorUnitario,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarSaldoEstoque = `-- name: ListarSaldoEstoque :many
SELECT 
    e.id_epi, 
    p.nome AS nome_epi,
    SUM(e.quantidade_atual)::int AS quantidade_atual,
    SUM(e.valor_unitario * e.quantidade_atual)::float AS saldo_atual,
    COUNT(*) OVER() AS total_geral
FROM entrada_epi_item e
INNER JOIN epi p ON e.id_epi = p.id
WHERE e.tenant_id = $3
  AND e.ativo = TRUE
  AND (p.fabricante = $4 OR $4 IS NULL)
GROUP BY e.id_epi, p.nome
LIMIT $1 OFFSET $2
`

type ListarSaldoEstoqueParams struct {
	Limit      int32
	Offset     int32
	TenantID   int32
	Fabricante pgtype.Text
}

type ListarSaldoEstoqueRow struct {
	IDEpi           int32
	NomeEpi         string
	QuantidadeAtual int32
	SaldoAtual      float64
	TotalGeral      int64
}

func (q *Queries) ListarSaldoEstoque(ctx context.Context, arg ListarSaldoEstoqueParams) ([]ListarSaldoEstoqueRow, error) {
	rows, err := q.db.Query(ctx, listarSaldoEstoque,
		arg.Limit,
		arg.Offset,
		arg.TenantID,
		arg.Fabricante,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarSaldoEstoqueRow
	for rows.Next() {
		var i ListarSaldoEstoqueRow
		if err := rows.Scan(
			&i.IDEpi,
			&i.NomeEpi,
			&i.QuantidadeAtual,
			&i.SaldoAtual,
			&i.TotalGeral,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registrarItemEntrega = `-- name: RegistrarItemEntrega :exec
INSERT INTO epis_entregues (
    tenant_id, 
    id_epi, 
    id_tamanho, 
    quantidade, 
    id_entrega_cabecalho, 
    id_entrada_item
) 
VALUES ($1, $2, $3, $4, $5, $6)
`

type RegistrarItemEntregaParams struct {
	TenantID           int32
	IDEpi              int32
	IDTamanho          int32
	Quantidade         int32
	IDEntregaCabecalho int32
	IDEntradaItem      int32
}

func (q *Queries) RegistrarItemEntrega(ctx context.Context, arg RegistrarItemEntregaParams) error {
	_, err := q.db.Exec(ctx, registrarItemEntrega,
		arg.TenantID,
		arg.IDEpi,
		arg.IDTamanho,
		arg.Quantidade,
		arg.IDEntregaCabecalho,
		arg.IDEntradaItem,
	)
	return err
}

const reporEstoqueLote = `-- name: ReporEstoqueLote :execrows
UPDATE entrada_epi_item 
SET quantidade_atual = quantidade_atual + $1 
WHERE id = $2 
  AND tenant_id = $3 
  AND ativo = TRUE
`

type ReporEstoqueLoteParams struct {
	QuantidadeAtual int32
	ID              int32
	TenantID        int32
}

func (q *Queries) ReporEstoqueLote(ctx context.Context, arg ReporEstoqueLoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, reporEstoqueLote, arg.QuantidadeAtual, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
