// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Funcao.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFuncao = `-- name: AddFuncao :exec
INSERT INTO funcao (tenant_id, nome, IdDepartamento) 
VALUES ($1, $2, $3)
`

type AddFuncaoParams struct {
	TenantID       int32
	Nome           string
	Iddepartamento int32
}

func (q *Queries) AddFuncao(ctx context.Context, arg AddFuncaoParams) error {
	_, err := q.db.Exec(ctx, addFuncao, arg.TenantID, arg.Nome, arg.Iddepartamento)
	return err
}

const buscarFuncao = `-- name: BuscarFuncao :one
SELECT 
    f.id, 
    f.nome, 
    f.IdDepartamento, 
    d.nome as departamento_nome
FROM funcao f
INNER JOIN departamento d ON f.IdDepartamento = d.id
WHERE f.id = $1 
  AND f.tenant_id = $2 -- SEGURANÇA
  AND f.ativo = TRUE
`

type BuscarFuncaoParams struct {
	ID       int32
	TenantID int32
}

type BuscarFuncaoRow struct {
	ID               int32
	Nome             string
	Iddepartamento   int32
	DepartamentoNome string
}

func (q *Queries) BuscarFuncao(ctx context.Context, arg BuscarFuncaoParams) (BuscarFuncaoRow, error) {
	row := q.db.QueryRow(ctx, buscarFuncao, arg.ID, arg.TenantID)
	var i BuscarFuncaoRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Iddepartamento,
		&i.DepartamentoNome,
	)
	return i, err
}

const buscarTodasFuncoes = `-- name: BuscarTodasFuncoes :many
SELECT 
    f.id, 
    f.nome, 
    f.IdDepartamento, 
    d.nome as departamento_nome,
    COUNT(*) OVER() AS total_geral
FROM funcao f
INNER JOIN departamento d ON f.IdDepartamento = d.id
WHERE f.tenant_id = $3 -- SEGURANÇA
  AND ($4::text IS NULL OR f.nome ILIKE '%' || $4 || '%')
  AND ($5::int IS NULL OR f.id = $5::int)
  AND (
    ($6::boolean IS FALSE AND f.deletado_em IS NULL) OR
    ($6::boolean IS TRUE AND f.deletado_em IS NOT NULL)
  )
  AND ($7::text IS NULL OR d.nome ILIKE '%' || $7 || '%')
ORDER BY f.nome ASC
LIMIT $1 OFFSET $2
`

type BuscarTodasFuncoesParams struct {
	Limit            int32
	Offset           int32
	TenantID         int32
	Nome             pgtype.Text
	ID               pgtype.Int4
	Cancelados       bool
	NomeDepartamento pgtype.Text
}

type BuscarTodasFuncoesRow struct {
	ID               int32
	Nome             string
	Iddepartamento   int32
	DepartamentoNome string
	TotalGeral       int64
}

func (q *Queries) BuscarTodasFuncoes(ctx context.Context, arg BuscarTodasFuncoesParams) ([]BuscarTodasFuncoesRow, error) {
	rows, err := q.db.Query(ctx, buscarTodasFuncoes,
		arg.Limit,
		arg.Offset,
		arg.TenantID,
		arg.Nome,
		arg.ID,
		arg.Cancelados,
		arg.NomeDepartamento,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarTodasFuncoesRow
	for rows.Next() {
		var i BuscarTodasFuncoesRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Iddepartamento,
			&i.DepartamentoNome,
			&i.TotalGeral,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletarFuncao = `-- name: DeletarFuncao :execrows
UPDATE funcao
SET ativo = FALSE,
    deletado_em = current_date
WHERE id = $1 
  AND tenant_id = $2 -- SEGURANÇA
  AND ativo = TRUE
`

type DeletarFuncaoParams struct {
	ID       int32
	TenantID int32
}

func (q *Queries) DeletarFuncao(ctx context.Context, arg DeletarFuncaoParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletarFuncao, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFuncao = `-- name: UpdateFuncao :execrows
UPDATE funcao
SET nome = $2
WHERE id = $1 
  AND tenant_id = $3 -- SEGURANÇA
  AND ativo = TRUE
`

type UpdateFuncaoParams struct {
	ID       int32
	Nome     string
	TenantID int32
}

func (q *Queries) UpdateFuncao(ctx context.Context, arg UpdateFuncaoParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFuncao, arg.ID, arg.Nome, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
