// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: Funcionarios.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFuncionario = `-- name: AddFuncionario :exec
INSERT INTO funcionario (tenant_id, nome, IdDepartamento, IdFuncao) 
VALUES ($1, $2, $3, $4)
`

type AddFuncionarioParams struct {
	TenantID       int32
	Nome           string
	Iddepartamento int32
	Idfuncao       int32
}

func (q *Queries) AddFuncionario(ctx context.Context, arg AddFuncionarioParams) error {
	_, err := q.db.Exec(ctx, addFuncionario,
		arg.TenantID,
		arg.Nome,
		arg.Iddepartamento,
		arg.Idfuncao,
	)
	return err
}

const buscaFuncionario = `-- name: BuscaFuncionario :one
SELECT 
    fn.id, 
    fn.nome, 
    fn.matricula, 
    fn.IdDepartamento, 
    d.nome as departamento_nome,
    fn.IdFuncao, 
    f.nome as funcao_nome
FROM funcionario fn
INNER JOIN departamento d ON fn.IdDepartamento = d.id
INNER JOIN funcao f ON fn.IdFuncao = f.id
WHERE fn.matricula = $1 
  AND fn.tenant_id = $2 -- IMPORTANTE: Matrícula só é única dentro do tenant
  AND fn.ativo = TRUE
`

type BuscaFuncionarioParams struct {
	Matricula int32
	TenantID  int32
}

type BuscaFuncionarioRow struct {
	ID               int32
	Nome             string
	Matricula        int32
	Iddepartamento   int32
	DepartamentoNome string
	Idfuncao         int32
	FuncaoNome       string
}

func (q *Queries) BuscaFuncionario(ctx context.Context, arg BuscaFuncionarioParams) (BuscaFuncionarioRow, error) {
	row := q.db.QueryRow(ctx, buscaFuncionario, arg.Matricula, arg.TenantID)
	var i BuscaFuncionarioRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Matricula,
		&i.Iddepartamento,
		&i.DepartamentoNome,
		&i.Idfuncao,
		&i.FuncaoNome,
	)
	return i, err
}

const buscaFuncionarioCompleto = `-- name: BuscaFuncionarioCompleto :many
SELECT
    fn.id, 
    fn.nome, 
    fn.matricula, 
    fn.IdFuncao, 
    f.nome as funcao_nome,
    fn.IdDepartamento, 
    d.nome as departamento_nome
FROM funcionario fn
INNER JOIN departamento d ON fn.IdDepartamento = d.id
INNER JOIN funcao f ON fn.IdFuncao = f.id
WHERE fn.tenant_id = $1 
  AND fn.ativo = TRUE
`

type BuscaFuncionarioCompletoRow struct {
	ID               int32
	Nome             string
	Matricula        int32
	Idfuncao         int32
	FuncaoNome       string
	Iddepartamento   int32
	DepartamentoNome string
}

func (q *Queries) BuscaFuncionarioCompleto(ctx context.Context, tenantID int32) ([]BuscaFuncionarioCompletoRow, error) {
	rows, err := q.db.Query(ctx, buscaFuncionarioCompleto, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscaFuncionarioCompletoRow
	for rows.Next() {
		var i BuscaFuncionarioCompletoRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Matricula,
			&i.Idfuncao,
			&i.FuncaoNome,
			&i.Iddepartamento,
			&i.DepartamentoNome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const buscaFuncionarioDashbord = `-- name: BuscaFuncionarioDashbord :many
SELECT id, nome, matricula
FROM funcionario
WHERE tenant_id = $1 
  AND ativo = TRUE 
  order by nome asc
`

type BuscaFuncionarioDashbordRow struct {
	ID        int32
	Nome      string
	Matricula int32
}

func (q *Queries) BuscaFuncionarioDashbord(ctx context.Context, tenantID int32) ([]BuscaFuncionarioDashbordRow, error) {
	rows, err := q.db.Query(ctx, buscaFuncionarioDashbord, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscaFuncionarioDashbordRow
	for rows.Next() {
		var i BuscaFuncionarioDashbordRow
		if err := rows.Scan(&i.ID, &i.Nome, &i.Matricula); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const buscaFuncionarioPorId = `-- name: BuscaFuncionarioPorId :one
SELECT 
    fn.id, 
    fn.nome, 
    fn.matricula, 
    fn.IdDepartamento, 
    d.nome as departamento_nome,
    fn.IdFuncao, 
    f.nome as funcao_nome
FROM funcionario fn
INNER JOIN departamento d ON fn.IdDepartamento = d.id
INNER JOIN funcao f ON fn.IdFuncao = f.id
WHERE fn.id = $1 
  AND fn.tenant_id = $2 -- SEGURANÇA
  AND fn.ativo = TRUE
`

type BuscaFuncionarioPorIdParams struct {
	ID       int32
	TenantID int32
}

type BuscaFuncionarioPorIdRow struct {
	ID               int32
	Nome             string
	Matricula        int32
	Iddepartamento   int32
	DepartamentoNome string
	Idfuncao         int32
	FuncaoNome       string
}

func (q *Queries) BuscaFuncionarioPorId(ctx context.Context, arg BuscaFuncionarioPorIdParams) (BuscaFuncionarioPorIdRow, error) {
	row := q.db.QueryRow(ctx, buscaFuncionarioPorId, arg.ID, arg.TenantID)
	var i BuscaFuncionarioPorIdRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Matricula,
		&i.Iddepartamento,
		&i.DepartamentoNome,
		&i.Idfuncao,
		&i.FuncaoNome,
	)
	return i, err
}

const buscarTodosFuncionarios = `-- name: BuscarTodosFuncionarios :many
SELECT 
    fn.id, 
    fn.nome, 
    -- Formatação para exibição
    CASE 
        WHEN fn.matricula < 10000 THEN LPAD(fn.matricula::text, 4, '0') 
        ELSE fn.matricula::text 
    END AS matricula,
    fn.IdDepartamento, 
    d.nome as departamento_nome,
    fn.IdFuncao, 
    f.nome as funcao_nome,
    COUNT(*) OVER() AS total_geral
FROM funcionario fn
INNER JOIN departamento d ON fn.IdDepartamento = d.id
INNER JOIN funcao f ON fn.IdFuncao = f.id
WHERE fn.tenant_id = $3 
  AND ($4::int IS NULL OR fn.id = $4::int)
  -- Formatação aplicada também na hora da busca para o ILIKE bater certinho
  AND (
      $5::text IS NULL OR 
      (
          CASE 
              WHEN fn.matricula < 10000 THEN LPAD(fn.matricula::text, 4, '0') 
              ELSE fn.matricula::text 
          END
      ) ILIKE '%' || $5 || '%'
  )
  AND ($6::text IS NULL OR fn.nome ILIKE '%' || $6 || '%')
  AND (
    ($7::boolean IS FALSE AND fn.deletado_em IS NULL) OR
    ($7::boolean IS TRUE AND fn.deletado_em IS NOT NULL)
  )
ORDER BY fn.nome ASC
LIMIT $1 OFFSET $2
`

type BuscarTodosFuncionariosParams struct {
	Limit      int32
	Offset     int32
	TenantID   int32
	ID         pgtype.Int4
	Matricula  pgtype.Text
	Nome       pgtype.Text
	Cancelados bool
}

type BuscarTodosFuncionariosRow struct {
	ID               int32
	Nome             string
	Matricula        string
	Iddepartamento   int32
	DepartamentoNome string
	Idfuncao         int32
	FuncaoNome       string
	TotalGeral       int64
}

func (q *Queries) BuscarTodosFuncionarios(ctx context.Context, arg BuscarTodosFuncionariosParams) ([]BuscarTodosFuncionariosRow, error) {
	rows, err := q.db.Query(ctx, buscarTodosFuncionarios,
		arg.Limit,
		arg.Offset,
		arg.TenantID,
		arg.ID,
		arg.Matricula,
		arg.Nome,
		arg.Cancelados,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarTodosFuncionariosRow
	for rows.Next() {
		var i BuscarTodosFuncionariosRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Matricula,
			&i.Iddepartamento,
			&i.DepartamentoNome,
			&i.Idfuncao,
			&i.FuncaoNome,
			&i.TotalGeral,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletarFuncionario = `-- name: DeletarFuncionario :execrows
UPDATE funcionario
SET ativo = FALSE,
    deletado_em = current_date
WHERE id = $1 
  AND tenant_id = $2 -- SEGURANÇA
  AND ativo = TRUE
`

type DeletarFuncionarioParams struct {
	ID       int32
	TenantID int32
}

func (q *Queries) DeletarFuncionario(ctx context.Context, arg DeletarFuncionarioParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletarFuncionario, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFuncionarioDepartamento = `-- name: UpdateFuncionarioDepartamento :execrows
UPDATE funcionario
SET IdDepartamento = $2
WHERE id = $1 
  AND tenant_id = $3 -- SEGURANÇA
  AND ativo = TRUE
`

type UpdateFuncionarioDepartamentoParams struct {
	ID             int32
	Iddepartamento int32
	TenantID       int32
}

func (q *Queries) UpdateFuncionarioDepartamento(ctx context.Context, arg UpdateFuncionarioDepartamentoParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFuncionarioDepartamento, arg.ID, arg.Iddepartamento, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFuncionarioFuncao = `-- name: UpdateFuncionarioFuncao :execrows
UPDATE funcionario
SET IdFuncao = $2
WHERE id = $1 
  AND tenant_id = $3 -- SEGURANÇA
  AND ativo = TRUE
`

type UpdateFuncionarioFuncaoParams struct {
	ID       int32
	Idfuncao int32
	TenantID int32
}

func (q *Queries) UpdateFuncionarioFuncao(ctx context.Context, arg UpdateFuncionarioFuncaoParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFuncionarioFuncao, arg.ID, arg.Idfuncao, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFuncionarioNome = `-- name: UpdateFuncionarioNome :execrows
UPDATE funcionario
SET nome = $2
WHERE id = $1 
  AND tenant_id = $3 -- SEGURANÇA
  AND ativo = TRUE
`

type UpdateFuncionarioNomeParams struct {
	ID       int32
	Nome     string
	TenantID int32
}

func (q *Queries) UpdateFuncionarioNome(ctx context.Context, arg UpdateFuncionarioNomeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFuncionarioNome, arg.ID, arg.Nome, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
