// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Departamento struct {
	ID         int32
	TenantID   int32
	Nome       string
	Ativo      bool
	DeletadoEm pgtype.Timestamp
}

type Devolucao struct {
	ID                             int32
	TenantID                       int32
	Idepi                          int32
	Idfuncionario                  int32
	Idmotivo                       int32
	DataDevolucao                  pgtype.Date
	Idtamanho                      int32
	Quantidadeadevolver            int32
	Idepinovo                      pgtype.Int4
	Idtamanhonovo                  pgtype.Int4
	Quantidadenova                 pgtype.Int4
	CanceladaEm                    pgtype.Timestamp
	AssinaturaDigital              string
	Ativo                          bool
	IDUsuarioCancelamento          pgtype.Int4
	IDUsuarioDevolucaoCancelamento pgtype.Int4
	TokenValidacao                 pgtype.Text
}

type Empresa struct {
	ID           int32
	NomeFantasia string
	RazaoSocial  string
	Cnpj         string
	Subdominio   string
	Ativo        bool
	CriadoEm     pgtype.Timestamp
}

type EntradaEpiItem struct {
	ID                    int32
	TenantID              int32
	EntradaNfID           int32
	IDEpi                 int32
	IDTamanho             int32
	Quantidade            int32
	QuantidadeAtual       int32
	DataFabricacao        pgtype.Date
	DataValidade          pgtype.Date
	Lote                  string
	ValorUnitario         pgtype.Numeric
	CanceladaEm           pgtype.Timestamp
	Ativo                 bool
	IDUsuarioCriacao      int32
	IDUsuarioCancelamento pgtype.Int4
}

type EntradaNf struct {
	ID                    int32
	TenantID              int32
	NotaFiscalNumero      string
	NotaFiscalSerie       pgtype.Text
	DataEmissao           pgtype.Date
	DataRegistro          pgtype.Timestamp
	Ativo                 bool
	IDUsuarioCriacao      int32
	IDUsuarioCancelamento pgtype.Int4
	CanceladaEm           pgtype.Timestamp
	Idfornecedor          int32
}

type EntregaEpi struct {
	ID                           int32
	TenantID                     int32
	Idfuncionario                int32
	DataEntrega                  pgtype.Date
	Assinatura                   string
	Idtroca                      pgtype.Int4
	CanceladaEm                  pgtype.Timestamp
	Ativo                        bool
	TokenValidacao               pgtype.Text
	IDUsuarioEntrega             pgtype.Int4
	IDUsuarioEntregaCancelamento pgtype.Int4
}

type Epi struct {
	ID             int32
	TenantID       int32
	Nome           string
	Fabricante     string
	Ca             string
	Descricao      string
	ValidadeCa     pgtype.Date
	Idtipoprotecao int32
	AlertaMinimo   int32
	Ativo          bool
	DeletadoEm     pgtype.Timestamp
}

type EpisEntregue struct {
	ID                 int32
	TenantID           int32
	IDEntregaCabecalho int32
	IDEntradaItem      int32
	IDEpi              int32
	IDTamanho          int32
	Quantidade         int32
	Ativo              bool
	DeletadoEm         pgtype.Timestamp
}

type Fornecedore struct {
	ID                int32
	TenantID          int32
	RazaoSocial       string
	NomeFantasia      string
	Cnpj              string
	InscricaoEstadual string
	Ativo             pgtype.Bool
	CanceladoEm       pgtype.Timestamp
}

type Funcao struct {
	ID             int32
	TenantID       int32
	Nome           string
	Iddepartamento int32
	Ativo          bool
	DeletadoEm     pgtype.Timestamp
}

type Funcionario struct {
	ID             int32
	TenantID       int32
	Nome           string
	Matricula      int32
	Idfuncao       int32
	Iddepartamento int32
	Ativo          bool
	DeletadoEm     pgtype.Timestamp
}

type MotivoDevolucao struct {
	ID         int32
	TenantID   int32
	Motivo     string
	Ativo      bool
	DeletadoEm pgtype.Timestamp
}

type Tamanho struct {
	ID         int32
	TenantID   int32
	Tamanho    string
	Ativo      bool
	DeletadoEm pgtype.Timestamp
}

type TamanhosEpi struct {
	ID         int32
	TenantID   int32
	Idepi      int32
	Idtamanho  int32
	Ativo      bool
	DeletadoEm pgtype.Timestamp
}

type TipoProtecao struct {
	ID         int32
	TenantID   int32
	Nome       string
	Ativo      bool
	DeletadoEm pgtype.Timestamp
}

type Usuario struct {
	ID        int32
	TenantID  int32
	Nome      string
	Email     string
	SenhaHash string
	Ativo     pgtype.Bool
	Role      pgtype.Text
}
