// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: MotivoDevolucao.sql

package repository

import (
	"context"
)

const addMotivoDevolucao = `-- name: AddMotivoDevolucao :one
INSERT INTO motivo_devolucao (tenant_id, motivo) 
VALUES ($1, $2)
returning id, motivo
`

type AddMotivoDevolucaoParams struct {
	TenantID int32
	Motivo   string
}

type AddMotivoDevolucaoRow struct {
	ID     int32
	Motivo string
}

func (q *Queries) AddMotivoDevolucao(ctx context.Context, arg AddMotivoDevolucaoParams) (AddMotivoDevolucaoRow, error) {
	row := q.db.QueryRow(ctx, addMotivoDevolucao, arg.TenantID, arg.Motivo)
	var i AddMotivoDevolucaoRow
	err := row.Scan(&i.ID, &i.Motivo)
	return i, err
}

const buscaMotivoDevolucao = `-- name: BuscaMotivoDevolucao :one
SELECT id, motivo 
FROM motivo_devolucao 
WHERE id = $1 
  AND tenant_id = $2 -- SEGURANÇA
  AND ativo = TRUE 
LIMIT 1
`

type BuscaMotivoDevolucaoParams struct {
	ID       int32
	TenantID int32
}

type BuscaMotivoDevolucaoRow struct {
	ID     int32
	Motivo string
}

func (q *Queries) BuscaMotivoDevolucao(ctx context.Context, arg BuscaMotivoDevolucaoParams) (BuscaMotivoDevolucaoRow, error) {
	row := q.db.QueryRow(ctx, buscaMotivoDevolucao, arg.ID, arg.TenantID)
	var i BuscaMotivoDevolucaoRow
	err := row.Scan(&i.ID, &i.Motivo)
	return i, err
}

const buscaTodosMotivosDevolucao = `-- name: BuscaTodosMotivosDevolucao :many
SELECT id, motivo 
FROM motivo_devolucao 
WHERE tenant_id = $1 -- SEGURANÇA: Lista apenas os motivos desta empresa
  AND ativo = TRUE
ORDER BY motivo ASC
`

type BuscaTodosMotivosDevolucaoRow struct {
	ID     int32
	Motivo string
}

func (q *Queries) BuscaTodosMotivosDevolucao(ctx context.Context, tenantID int32) ([]BuscaTodosMotivosDevolucaoRow, error) {
	rows, err := q.db.Query(ctx, buscaTodosMotivosDevolucao, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscaTodosMotivosDevolucaoRow
	for rows.Next() {
		var i BuscaTodosMotivosDevolucaoRow
		if err := rows.Scan(&i.ID, &i.Motivo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteMotivoDevolucao = `-- name: DeleteMotivoDevolucao :execrows
UPDATE motivo_devolucao
SET ativo = FALSE,
    deletado_em = current_date
WHERE id = $1 
  AND tenant_id = $2 -- SEGURANÇA
  AND ativo = TRUE
`

type DeleteMotivoDevolucaoParams struct {
	ID       int32
	TenantID int32
}

func (q *Queries) DeleteMotivoDevolucao(ctx context.Context, arg DeleteMotivoDevolucaoParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMotivoDevolucao, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
