// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: planos.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPlano = `-- name: AddPlano :one
INSERT INTO planos (nome, mensalidade, limite_funcionarios, limite_usuarios, limite_epis, status, descricao)
    VALUES ($1, $2, $3, $4, $5, $6, $7)
    RETURNING id
`

type AddPlanoParams struct {
	Nome               string
	Mensalidade        pgtype.Numeric
	LimiteFuncionarios pgtype.Int4
	LimiteUsuarios     pgtype.Int4
	LimiteEpis         pgtype.Int4
	Status             pgtype.Text
	Descricao          string
}

func (q *Queries) AddPlano(ctx context.Context, arg AddPlanoParams) (int32, error) {
	row := q.db.QueryRow(ctx, addPlano,
		arg.Nome,
		arg.Mensalidade,
		arg.LimiteFuncionarios,
		arg.LimiteUsuarios,
		arg.LimiteEpis,
		arg.Status,
		arg.Descricao,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const buscaPlanos = `-- name: BuscaPlanos :many
SELECT id, nome, mensalidade, limite_funcionarios, limite_usuarios, limite_epis, status, descricao
FROM planos
WHERE status = 'Ativo'
ORDER BY nome ASC
`

type BuscaPlanosRow struct {
	ID                 int32
	Nome               string
	Mensalidade        pgtype.Numeric
	LimiteFuncionarios pgtype.Int4
	LimiteUsuarios     pgtype.Int4
	LimiteEpis         pgtype.Int4
	Status             pgtype.Text
	Descricao          string
}

func (q *Queries) BuscaPlanos(ctx context.Context) ([]BuscaPlanosRow, error) {
	rows, err := q.db.Query(ctx, buscaPlanos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscaPlanosRow
	for rows.Next() {
		var i BuscaPlanosRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Mensalidade,
			&i.LimiteFuncionarios,
			&i.LimiteUsuarios,
			&i.LimiteEpis,
			&i.Status,
			&i.Descricao,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
