// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: Tamanhos.sql

package repository

import (
	"context"
)

const addTamanho = `-- name: AddTamanho :exec
INSERT INTO tamanho (tenant_id, tamanho) 
VALUES ($1, $2)
`

type AddTamanhoParams struct {
	TenantID int32
	Tamanho  string
}

func (q *Queries) AddTamanho(ctx context.Context, arg AddTamanhoParams) error {
	_, err := q.db.Exec(ctx, addTamanho, arg.TenantID, arg.Tamanho)
	return err
}

const buscarTamanho = `-- name: BuscarTamanho :one
SELECT id, tamanho 
FROM tamanho 
WHERE id = $1 
  AND tenant_id = $2 -- SEGURANÇA
  AND ativo = TRUE 
LIMIT 1
`

type BuscarTamanhoParams struct {
	ID       int32
	TenantID int32
}

type BuscarTamanhoRow struct {
	ID      int32
	Tamanho string
}

func (q *Queries) BuscarTamanho(ctx context.Context, arg BuscarTamanhoParams) (BuscarTamanhoRow, error) {
	row := q.db.QueryRow(ctx, buscarTamanho, arg.ID, arg.TenantID)
	var i BuscarTamanhoRow
	err := row.Scan(&i.ID, &i.Tamanho)
	return i, err
}

const buscarTamanhosComEstoquePorEpi = `-- name: BuscarTamanhosComEstoquePorEpi :many
SELECT DISTINCT t.id, t.tamanho, eei.id_epi
FROM tamanho t
INNER JOIN entrada_epi_item eei ON t.id = eei.id_tamanho
WHERE eei.id_epi = $1 
  AND eei.tenant_id = $2 
  AND eei.quantidade_atual > 0
  AND eei.ativo = TRUE
ORDER BY t.tamanho ASC
`

type BuscarTamanhosComEstoquePorEpiParams struct {
	IDEpi    int32
	TenantID int32
}

type BuscarTamanhosComEstoquePorEpiRow struct {
	ID      int32
	Tamanho string
	IDEpi   int32
}

func (q *Queries) BuscarTamanhosComEstoquePorEpi(ctx context.Context, arg BuscarTamanhosComEstoquePorEpiParams) ([]BuscarTamanhosComEstoquePorEpiRow, error) {
	rows, err := q.db.Query(ctx, buscarTamanhosComEstoquePorEpi, arg.IDEpi, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarTamanhosComEstoquePorEpiRow
	for rows.Next() {
		var i BuscarTamanhosComEstoquePorEpiRow
		if err := rows.Scan(&i.ID, &i.Tamanho, &i.IDEpi); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const buscarTamanhosPorIdEpi = `-- name: BuscarTamanhosPorIdEpi :many
SELECT t.id, t.tamanho, te.IdEpi
FROM tamanho t
INNER JOIN tamanhos_epis te ON t.id = te.IdTamanho
WHERE te.IdEpi = $1 
  AND te.tenant_id = $2 -- SEGURANÇA: Garante que a relação é desta empresa
  AND te.ativo = TRUE
  AND t.tenant_id = $2 -- O sqlc sabe que é o MESMO tenant_id de cima!
  AND t.ativo = TRUE
ORDER BY t.tamanho ASC
`

type BuscarTamanhosPorIdEpiParams struct {
	IDEpi    int32
	TenantID int32
}

type BuscarTamanhosPorIdEpiRow struct {
	ID      int32
	Tamanho string
	Idepi   int32
}

func (q *Queries) BuscarTamanhosPorIdEpi(ctx context.Context, arg BuscarTamanhosPorIdEpiParams) ([]BuscarTamanhosPorIdEpiRow, error) {
	rows, err := q.db.Query(ctx, buscarTamanhosPorIdEpi, arg.IDEpi, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarTamanhosPorIdEpiRow
	for rows.Next() {
		var i BuscarTamanhosPorIdEpiRow
		if err := rows.Scan(&i.ID, &i.Tamanho, &i.Idepi); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const buscarTodosTamanhos = `-- name: BuscarTodosTamanhos :many
SELECT id, tamanho 
FROM tamanho 
WHERE tenant_id = $1 -- SEGURANÇA: Lista apenas tamanhos desta empresa
  AND ativo = TRUE
ORDER BY tamanho ASC
`

type BuscarTodosTamanhosRow struct {
	ID      int32
	Tamanho string
}

func (q *Queries) BuscarTodosTamanhos(ctx context.Context, tenantID int32) ([]BuscarTodosTamanhosRow, error) {
	rows, err := q.db.Query(ctx, buscarTodosTamanhos, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarTodosTamanhosRow
	for rows.Next() {
		var i BuscarTodosTamanhosRow
		if err := rows.Scan(&i.ID, &i.Tamanho); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletarTamanho = `-- name: DeletarTamanho :execrows
UPDATE tamanho
SET ativo = FALSE,
    deletado_em = current_date
WHERE id = $1 
  AND tenant_id = $2 -- SEGURANÇA
  AND ativo = TRUE
`

type DeletarTamanhoParams struct {
	ID       int32
	TenantID int32
}

func (q *Queries) DeletarTamanho(ctx context.Context, arg DeletarTamanhoParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletarTamanho, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEpiNosTamanhos = `-- name: UpdateEpiNosTamanhos :execrows

UPDATE tamanhos_epis
SET IdEpi = $2
WHERE IdEpi = $1 
  AND tenant_id = $3 -- SEGURANÇA: Obrigatório
  AND ativo = TRUE
`

type UpdateEpiNosTamanhosParams struct {
	Idepi    int32
	Idepi_2  int32
	TenantID int32
}

// SEGURANÇA: Garante que só pode deletar tamanhos da própria empresa
// Esta query atualiza a associação na tabela muitos-para-muitos
func (q *Queries) UpdateEpiNosTamanhos(ctx context.Context, arg UpdateEpiNosTamanhosParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEpiNosTamanhos, arg.Idepi, arg.Idepi_2, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
