// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: Usuario.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const buscarPorIdUsuario = `-- name: BuscarPorIdUsuario :one
SELECT id, nome, email, ativo, role
FROM usuarios
WHERE id = $1 
  AND tenant_id = $2 -- SEGURANÇA
  AND ativo = TRUE
LIMIT 1
`

type BuscarPorIdUsuarioParams struct {
	ID       int32
	TenantID int32
}

type BuscarPorIdUsuarioRow struct {
	ID    int32
	Nome  string
	Email string
	Ativo pgtype.Bool
	Role  pgtype.Text
}

func (q *Queries) BuscarPorIdUsuario(ctx context.Context, arg BuscarPorIdUsuarioParams) (BuscarPorIdUsuarioRow, error) {
	row := q.db.QueryRow(ctx, buscarPorIdUsuario, arg.ID, arg.TenantID)
	var i BuscarPorIdUsuarioRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.Ativo,
		&i.Role,
	)
	return i, err
}

const buscarTodosUsuarios = `-- name: BuscarTodosUsuarios :many
SELECT id, nome, email, ativo, role
FROM usuarios
WHERE tenant_id = $1 -- SEGURANÇA: Lista apenas usuários desta empresa
  AND ativo = TRUE
`

type BuscarTodosUsuariosRow struct {
	ID    int32
	Nome  string
	Email string
	Ativo pgtype.Bool
	Role  pgtype.Text
}

func (q *Queries) BuscarTodosUsuarios(ctx context.Context, tenantID int32) ([]BuscarTodosUsuariosRow, error) {
	rows, err := q.db.Query(ctx, buscarTodosUsuarios, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarTodosUsuariosRow
	for rows.Next() {
		var i BuscarTodosUsuariosRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Email,
			&i.Ativo,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const buscarUsuarioPorEmail = `-- name: BuscarUsuarioPorEmail :one
SELECT id, nome, email, senha_hash, tenant_id, role
FROM usuarios
WHERE email = $1 
  AND tenant_id = $2 
  AND ativo = TRUE
LIMIT 1
`

type BuscarUsuarioPorEmailParams struct {
	Email    string
	TenantID int32
}

type BuscarUsuarioPorEmailRow struct {
	ID        int32
	Nome      string
	Email     string
	SenhaHash string
	TenantID  int32
	Role      pgtype.Text
}

// Atenção: Se o email puder se repetir entre empresas, o tenant_id é OBRIGATÓRIO aqui.
func (q *Queries) BuscarUsuarioPorEmail(ctx context.Context, arg BuscarUsuarioPorEmailParams) (BuscarUsuarioPorEmailRow, error) {
	row := q.db.QueryRow(ctx, buscarUsuarioPorEmail, arg.Email, arg.TenantID)
	var i BuscarUsuarioPorEmailRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.TenantID,
		&i.Role,
	)
	return i, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO usuarios (tenant_id, nome, email, senha_hash, role) 
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserParams struct {
	TenantID  int32
	Nome      string
	Email     string
	SenhaHash string
	Role      pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.TenantID,
		arg.Nome,
		arg.Email,
		arg.SenhaHash,
		arg.Role,
	)
	return err
}

const deletarUsuario = `-- name: DeletarUsuario :execrows
UPDATE usuarios
SET ativo = FALSE
WHERE id = $1 
  AND tenant_id = $2 -- SEGURANÇA
  AND ativo = TRUE
`

type DeletarUsuarioParams struct {
	ID       int32
	TenantID int32
}

func (q *Queries) DeletarUsuario(ctx context.Context, arg DeletarUsuarioParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletarUsuario, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
