// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Usuario.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarUltimoAcesso = `-- name: AtualizarUltimoAcesso :execrows
update usuarios
set ultimo_acesso = now()
where id = $1 and tenant_id = $2
`

type AtualizarUltimoAcessoParams struct {
	ID       int32
	TenantID pgtype.Int4
}

func (q *Queries) AtualizarUltimoAcesso(ctx context.Context, arg AtualizarUltimoAcessoParams) (int64, error) {
	result, err := q.db.Exec(ctx, atualizarUltimoAcesso, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const buscarPorIdUsuario = `-- name: BuscarPorIdUsuario :one
SELECT id, nome, email, ativo, role
FROM usuarios
WHERE id = $1 
  AND tenant_id = $2 -- SEGURANÇA
  AND ativo = TRUE
LIMIT 1
`

type BuscarPorIdUsuarioParams struct {
	ID       int32
	TenantID pgtype.Int4
}

type BuscarPorIdUsuarioRow struct {
	ID    int32
	Nome  string
	Email string
	Ativo pgtype.Bool
	Role  pgtype.Text
}

func (q *Queries) BuscarPorIdUsuario(ctx context.Context, arg BuscarPorIdUsuarioParams) (BuscarPorIdUsuarioRow, error) {
	row := q.db.QueryRow(ctx, buscarPorIdUsuario, arg.ID, arg.TenantID)
	var i BuscarPorIdUsuarioRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.Ativo,
		&i.Role,
	)
	return i, err
}

const buscarTodosUsuarios = `-- name: BuscarTodosUsuarios :many
SELECT id, nome, email, role as cargo
FROM usuarios
WHERE tenant_id = $1 -- SEGURANÇA: Lista apenas usuários desta empresa
  AND ativo = TRUE
`

type BuscarTodosUsuariosRow struct {
	ID    int32
	Nome  string
	Email string
	Cargo pgtype.Text
}

func (q *Queries) BuscarTodosUsuarios(ctx context.Context, tenantID pgtype.Int4) ([]BuscarTodosUsuariosRow, error) {
	rows, err := q.db.Query(ctx, buscarTodosUsuarios, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarTodosUsuariosRow
	for rows.Next() {
		var i BuscarTodosUsuariosRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Email,
			&i.Cargo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const buscarUsuarioPorEmail = `-- name: BuscarUsuarioPorEmail :one
SELECT id, nome, email, senha_hash, tenant_id, role
FROM usuarios
WHERE email = $1 
  AND tenant_id = $2 
  AND ativo = TRUE
LIMIT 1
`

type BuscarUsuarioPorEmailParams struct {
	Email    string
	TenantID pgtype.Int4
}

type BuscarUsuarioPorEmailRow struct {
	ID        int32
	Nome      string
	Email     string
	SenhaHash string
	TenantID  pgtype.Int4
	Role      pgtype.Text
}

// Atenção: Se o email puder se repetir entre empresas, o tenant_id é OBRIGATÓRIO aqui.
func (q *Queries) BuscarUsuarioPorEmail(ctx context.Context, arg BuscarUsuarioPorEmailParams) (BuscarUsuarioPorEmailRow, error) {
	row := q.db.QueryRow(ctx, buscarUsuarioPorEmail, arg.Email, arg.TenantID)
	var i BuscarUsuarioPorEmailRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.TenantID,
		&i.Role,
	)
	return i, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO usuarios (tenant_id, nome, email, senha_hash, role) 
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserParams struct {
	TenantID  pgtype.Int4
	Nome      string
	Email     string
	SenhaHash string
	Role      pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.TenantID,
		arg.Nome,
		arg.Email,
		arg.SenhaHash,
		arg.Role,
	)
	return err
}

const deletarUsuario = `-- name: DeletarUsuario :execrows
UPDATE usuarios
SET ativo = FALSE
WHERE id = $1 
  AND tenant_id = $2 -- SEGURANÇA
  AND ativo = TRUE
`

type DeletarUsuarioParams struct {
	ID       int32
	TenantID pgtype.Int4
}

func (q *Queries) DeletarUsuario(ctx context.Context, arg DeletarUsuarioParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletarUsuario, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const mostrarUsuariosPainel = `-- name: MostrarUsuariosPainel :many
select tenant_id, nome, u.email, e.nome_fantasia as empresa,role as tipo,ativo, ultimo_acesso
from usuarios u
inner join empresas e on u.tenant_id = e.id
`

type MostrarUsuariosPainelRow struct {
	TenantID     pgtype.Int4
	Nome         string
	Email        string
	Empresa      string
	Tipo         pgtype.Text
	Ativo        pgtype.Bool
	UltimoAcesso pgtype.Timestamp
}

func (q *Queries) MostrarUsuariosPainel(ctx context.Context) ([]MostrarUsuariosPainelRow, error) {
	rows, err := q.db.Query(ctx, mostrarUsuariosPainel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MostrarUsuariosPainelRow
	for rows.Next() {
		var i MostrarUsuariosPainelRow
		if err := rows.Scan(
			&i.TenantID,
			&i.Nome,
			&i.Email,
			&i.Empresa,
			&i.Tipo,
			&i.Ativo,
			&i.UltimoAcesso,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recuperaLogin = `-- name: RecuperaLogin :one
select id from usuarios 
where email = $1 and tenant_id = $2 limit 1
`

type RecuperaLoginParams struct {
	Email    string
	TenantID pgtype.Int4
}

func (q *Queries) RecuperaLogin(ctx context.Context, arg RecuperaLoginParams) (int32, error) {
	row := q.db.QueryRow(ctx, recuperaLogin, arg.Email, arg.TenantID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const salvarTokenRecuperacao = `-- name: SalvarTokenRecuperacao :execrows
update usuarios
set token_recuperacao_senha = $1, token_expiracao = $2
where id = $3 and tenant_id = $4
`

type SalvarTokenRecuperacaoParams struct {
	TokenRecuperacaoSenha pgtype.Text
	TokenExpiracao        pgtype.Timestamp
	ID                    int32
	TenantID              pgtype.Int4
}

func (q *Queries) SalvarTokenRecuperacao(ctx context.Context, arg SalvarTokenRecuperacaoParams) (int64, error) {
	result, err := q.db.Exec(ctx, salvarTokenRecuperacao,
		arg.TokenRecuperacaoSenha,
		arg.TokenExpiracao,
		arg.ID,
		arg.TenantID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSenha = `-- name: UpdateSenha :execrows
update usuarios
set senha_hash = $1,
    token_recuperacao_senha = null,
    token_expiracao = null
where token_recuperacao_senha = $2 and tenant_id = $3 and token_expiracao > now()
`

type UpdateSenhaParams struct {
	SenhaHash             string
	TokenRecuperacaoSenha pgtype.Text
	TenantID              pgtype.Int4
}

func (q *Queries) UpdateSenha(ctx context.Context, arg UpdateSenhaParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSenha, arg.SenhaHash, arg.TokenRecuperacaoSenha, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
